var GAME_LEVELS = [
  
  ["xxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
   "xxxxxxxxxxx   xxxxxxxxxxxxxxx",
   "xxx    xx      xx   xxxxxxxxx",
   "xx     xx           xxxxxxxxx",
   "xx  @   xxh              xxxx",
   "xxx   #xx                xxxx",
   "xxxxxx            h  xxxxxxxx",
   "xxx         xxxx      xxxxxxx",
   "xxxx       xxxxx          xxx",
   "xxxxx        | xxxxx   o  xxx",
   "xxx!>           xxx       xxx",
   "xxxxx           xxx      xxxx",
   "xxxxxxxxx                xxxx",
   "xxxxxxxxx             xxxxxxx",
   "xxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
   "xxxxxxxxxxxxxxxxxxxxxxxxxxxxx"],

  ["xxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
   "xxx                       xxx",
   "xx                        <!x",
   "xx     xx          xxx  xxxxx",
   "xx      x  h  xxxxxx       xx",
   "x                  x     o xx",
   "x!>                xxxx    xx",
   "xxx  xx     xxxx      xxxxxxx",
   "xxxxxxxxh  xxxxx=         xxx",
   "xxxx xx                   xxx",
   "xxx   x           xxx     xxx",
   "xx    #       xxxxx         x",
   "x      xx       x           x",
   "x @    xx                  xx",
   "x     xxxx |           xxxxxx",
   "xxxxxxxxxxxxxxxxxxxxxxxxxxxxx"],
   
   ["xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
   "x      xxxxxxxx               xxxxxx  xx      xx         xx",
   "           xxxx                       x                   x",
   "             xxxx  xxxxxxxx           x  o               xx",
   "           #       xx|    xxxxxxx     x      xxxxxx      xx",
   "                            xxxxx    xxxxxxxxxxxxxxx  xxxxx",
   "           xxxx               xx                x       <!x",
   "           xxxxx   x                                      x",
   "          xxxxxxxxxx                                      x",
   "    @     xx   xxxxxx       xxxx  =     xxxxxxx           x",
   "x        xxx    xxxxxx        xxx           xxxx          x",
   "xxxxxxxxxxx     !xxxxxxx      x           xxxxx     h     x",
   "x   xx          v xxx|                    x            xxxx",
   "                   xx                    xxx        xxxxxxx",
   "                                       xxxx      xxxxxxxxxx",
   "                                         x                x",
   "                   xx        xx        <!xx               x",
   "                  xxx   xxxxxxxx         x               xx",
   "                   xxxxxx      xx^       x                x",
   "                  xx            x!       xx               x",
   "                          h     xx      xxx         o     x",
   "    o                                                     x",
   "                xxxxxxx              h                   xx",
   "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"]

];

if (typeof module != "undefined" && module.exports)
  module.exports = GAME_LEVELS;
